// frontend/secret_santa_frontend/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-card">
      <div class="login-logo">🎅 Тайный Санта</div>
      <form @submit.prevent="handleLogin">
        <div class="form-group">
          <label for="username">Имя пользователя</label>
          <input
            id="username"
            v-model="credentials.name"
            type="text"
            required
            placeholder="Введите ваше имя"
          />
        </div>
        <div class="form-group">
          <label for="password">Пароль</label>
          <input
            id="password"
            v-model="credentials.password"
            type="password"
            required
            placeholder="Введите ваш пароль"
          />
        </div>
        <button type="submit" class="btn btn-primary" style="width: 100%">Войти</button>
        <p v-if="error" style="color: var(--primary-color); margin-top: 1rem">
          {{ error }}
        </p>
      </form>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

export default {
  name: 'LoginView',
  setup() {
    const authStore = useAuthStore()
    const router = useRouter()
    const credentials = ref({
      name: '',
      password: '',
    })
    const error = ref('')

    const handleLogin = async () => {
      try {
        error.value = ''
        await authStore.login(credentials.value)
        router.push('/profile')
      } catch (err) {
        error.value = 'Ошибка входа. Проверьте имя пользователя и пароль.'
        console.error('Login error:', err)
      }
    }

    return {
      credentials,
      error,
      handleLogin,
    }
  },
}
</script>

// frontend/secret_santa_frontend/src/components/auth/Login/Login.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

import './Login.css';

export default function Login() {
    const navigate = useNavigate();
    const [name, setName] = useState('');
    const [password, setPassword] = useState('');
    const [message, setMessage] = useState(null);

    const handleLogin = async (e) => {
        e.preventDefault();

        try {
            const response = await fetch('/api/v1/auth/login', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ name, password }),
            });

            if (response.ok) {
                const data = await response.json();
                localStorage.setItem('token', data.token);
                localStorage.setItem('name', name);
                setMessage({ text: 'Вход выполнен успешно!', type: 'success' });
                navigate('/home')
            } else {
                const errorData = await response.json();
                setMessage({ text: errorData.message || 'Ошибка входа', type: 'error' });
            }
        } catch (err) {
            setMessage({ text: 'Ошибка входа', type: 'error' });
        }
    };

    return (
        <div className="login-page">
        <div className="login-container">
            <div className="login-card">
                <div className="login-header">Тайный Санта</div>

                <form onSubmit={handleLogin}>
                    <label htmlFor="name">Логин:</label>
                    <input
                        type="text"
                        id="name"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        required
                    />

                    <label htmlFor="password">Пароль:</label>
                    <input
                        type="password"
                        id="password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        required
                    />

                    <button type="submit">Войти</button>
                </form>

                {message && (
                    <div className={`message ${message.type}`}>
                        {message.text}
                    </div>
                )}
            </div>
        </div>
        </div>
    );
}
