// frontend/secret_santa_frontend/src/components/Sidebar/Sidebar.jsx
import React from "react";
import { NavLink } from "react-router-dom";
import "./Sidebar.css";

export default function Sidebar() {
    const navItems = [
        { path: "/wishlist", label: "Вишлист" },
        { path: "/events", label: "События" },
        {
            label: "Группы",
            submenu: [
                { path: "/groups", label: "Мои группы" },
                { path: "/groups/invitations", label: "Приглашения" },
            ],
        },
    ];

    return (
        <aside className="sidebar">
            <ul className="sidebar-list">
                {navItems.map((item) => (
                    <li key={item.label}>
                        {item.submenu ? (
                            <>
                                <div className="sidebar-group-header">{item.label}</div>
                                <ul className="sidebar-submenu">
                                    {item.submenu.map((sub) => (
                                        <li key={sub.path}>
                                            <NavLink
                                                to={sub.path}
                                                className={({ isActive }) =>
                                                    isActive ? "sidebar-link active" : "sidebar-link"
                                                }
                                            >
                                                {sub.label}
                                            </NavLink>
                                        </li>
                                    ))}
                                </ul>
                            </>
                        ) : (
                            <NavLink
                                to={item.path}
                                className={({ isActive }) =>
                                    isActive ? "sidebar-link active" : "sidebar-link"
                                }
                            >
                                {item.label}
                            </NavLink>
                        )}
                    </li>
                ))}
            </ul>
        </aside>
    );
}

// frontend/secret_santa_frontend/src/components/Sidebar.vue
<template>
  <nav class="sidebar">
    <ul>
      <li>
        <router-link to="/profile" :class="{ active: $route.path === '/profile' }">
          Профиль
        </router-link>
      </li>
      <li>
        <router-link to="/wishlist" :class="{ active: $route.path === '/wishlist' }">
          Вишлист
        </router-link>
      </li>
      <li>
        <router-link to="/events" :class="{ active: $route.path === '/events' }">
          Мои события
        </router-link>
      </li>
    </ul>
  </nav>
</template>

<script>
export default {
  name: 'AppSidebar'
}
</script>
